trigger:
  branches:
    include:
      - test

pool:
  name: laptop-agent

variables:
- group: dev-vars

stages:

- template: templates/source.yml

- template: templates/quality.yml

- template: templates/security.yml

- template: templates/publish.yml

- template: templates/integration.yml

- template: templates/terraform-validation.yml

- template: templates/terraform-security.yml

- template: templates/terraform-apply.yml

- template: templates/terraform-approval.yml