trigger:
  branches:
    include:
      - test

pool:
  name: laptop-agent

variables:
- group: dev-vars

stages:

- stage: Verify

  jobs:

  - job: ValidateAgent

    steps:

    - checkout: self

    - script: |
        echo "Pipeline Started"

        pwd

        ls -la

        git --version

        docker --version

        terraform version

        kubectl version --client

        aws --version

      displayName: Validate Tools

    - script: |
        echo ENV=$(ENV)
        echo REGION=$(AWS_REGION)
        echo CLUSTER=$(EKS_CLUSTER)

      displayName: Validate Variables