stages:

- stage: GitOpsDeployment
  displayName: "GitOps Deployment"
  dependsOn: KubernetesValidation
  condition: |
    ne(
      variables['TF_ACTION'],
      'destroy'
    )
  jobs:

  - job: Deploy
    displayName: "Install Argo And Deploy"

    pool:
      name: laptop-agent

    steps:
    - checkout: self


# CONNECT
    - script: |
        export AWS_DEFAULT_REGION=$(AWS_REGION)

        aws eks update-kubeconfig \
          --region $(AWS_REGION) \
          --name $(EKS_CLUSTER)

      displayName: "Connect Cluster"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)


# INSTALL ARGO
    - script: |

        kubectl create namespace argocd \
          --dry-run=client \
          -o yaml \
          | kubectl apply -f -

        kubectl apply \
          --server-side \
          --force-conflicts \
          -n argocd \
          -f \
          https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      displayName: "Install Argo"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)


# WAIT
    - script: |

        kubectl rollout status \
        deployment/argocd-server \
        -n argocd \
        --timeout=180s

      displayName: "Wait Argo"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)


# PASSWORD
    - script: |

        PASS=$(
          kubectl \
          -n argocd \
          get secret \
          argocd-initial-admin-secret \
          -o jsonpath="{.data.password}" \
          | base64 -d
        )

        echo ""
        echo "===================="
        echo "ARGO LOGIN"
        echo ""
        echo "RUN:"
        echo "kubectl port-forward svc/argocd-server -n argocd 8085:80"
        echo ""
        echo "URL:"
        echo "http://localhost:8085"
        echo ""
        echo "USER: admin"
        echo "PASS: $PASS"
        echo "===================="

      displayName: "Show Argo Login"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)


# CREATE APP
    - script: |
        kubectl apply \
          -f ./gitops/application.yaml

      displayName: "Create Application"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)


# VERIFY
    - script: |

        sleep 15
        kubectl get applications -n argocd
        kubectl get pods -A

      displayName: "Verify"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)


# SHOW APP URL

    - script: |

        echo ""
        echo "===================="
        echo "ARGO LOGIN"
        echo ""
        echo "RUN:"
        echo "kubectl port-forward svc/argocd-server -n argocd 8085:80"
        echo ""
        echo "URL:"
        echo "http://localhost:8085"
        echo ""
        echo "USER: admin"
        echo ""
        echo "PASSWORD:"
        echo "Retrieve locally using:"
        echo ""
        echo "kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d"
        echo ""
        echo "===================="

      displayName: "Show Argo Login"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)