stages:

- stage: HPA
  displayName: "Autoscaling"
  dependsOn: MetricsServer
  condition: |
    ne(
      variables['TF_ACTION'],
      'destroy'
    )

  jobs:

  - job: Configure
    pool:
      name: laptop-agent

    steps:
    - checkout: self

    - script: |

        aws eks update-kubeconfig \
        --region $(AWS_REGION) \
        --name $(EKS_CLUSTER)

      displayName: "Connect"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

    - script: |

        kubectl apply \
        -f k8s-specifications/hpa.yaml

      displayName: "Create HPA"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

    - script: |
        kubectl get hpa

      displayName: "Verify"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)