stages:

- stage: KubernetesValidation

  displayName: "Kubernetes Validation"

  dependsOn: TerraformProvision

  jobs:

  - job: ValidateCluster

    displayName: "Validate Kubernetes"

    pool:
      name: laptop-agent

    steps:

    - checkout: self

# CONFIGURE AWS + KUBECONFIG

    - script: |

        mkdir -p ~/.aws

        cat > ~/.aws/credentials <<EOF
        [default]
        aws_access_key_id=$(AWS_ACCESS_KEY_ID)
        aws_secret_access_key=$(AWS_SECRET_ACCESS_KEY)
        EOF

        cat > ~/.aws/config <<EOF
        [default]
        region=$(AWS_REGION)
        output=json
        EOF

        export AWS_PROFILE=default

        aws sts get-caller-identity

        aws eks update-kubeconfig \
        --region $(AWS_REGION) \
        --name $(EKS_CLUSTER)

      displayName: "Configure Cluster"

# VERIFY

    - script: |

        export AWS_PROFILE=default

        kubectl get nodes

        kubectl get ns

      displayName: "Validate Cluster"

# MANIFEST

    - script: |

        export AWS_PROFILE=default

        kubectl apply \
        --dry-run=client \
        --validate=false \
        -f k8s-specifications/

      displayName: "Manifest Validation"

# RBAC

    - script: |

        export AWS_PROFILE=default

        kubectl auth can-i get pods

      displayName: "RBAC Validation"

# SECRET

    - script: |

        export AWS_PROFILE=default

        kubectl get secrets

      displayName: "Secrets Validation"

# NETWORK

    - script: |

        export AWS_PROFILE=default

        kubectl get networkpolicy \
        --all-namespaces || true

      displayName: "Network Validation"

# CLEAN

    - script: |

        rm -rf ~/.aws

      condition: always()

      displayName: "Cleanup"