stages:

- stage: KubernetesValidation

  displayName: "Kubernetes Validation"

  dependsOn: TerraformProvision

  jobs:
  - job: ValidateCluster

    displayName: "Validate Kubernetes"

    pool:
      name: laptop-agent

    steps:
    - checkout: self

# CONNECT
    - script: |

        export AWS_DEFAULT_REGION=$(AWS_REGION)

        aws sts get-caller-identity

        aws eks update-kubeconfig \
          --region $(AWS_REGION) \
          --name $(EKS_CLUSTER)

      displayName: "Configure Cluster"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

# VERIFY

    - script: |
        kubectl get nodes

        kubectl get ns

      displayName: "Validate Cluster"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

# MANIFEST
    - script: |

        kubectl apply \
          --dry-run=client \
          --validate=false \
          -f k8s-specifications/

      displayName: "Manifest Validation"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)


# RBAC
    - script: |

        kubectl auth can-i get pods

      displayName: "RBAC Validation"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

# SECRETS
    - script: |
        kubectl get secrets

      displayName: "Secrets Validation"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

# NETWORK
    - script: |

        kubectl get networkpolicy \
          --all-namespaces || true

      displayName: "Network Validation"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)