stages:

- stage: MetricsServer
  displayName: "Install Metrics Server"
  dependsOn: GitOpsDeployment
  condition: |
    ne(
      variables['TF_ACTION'],
      'destroy'
    )
    
  jobs:

  - job: InstallMetrics

    displayName: "Install Metrics"

    pool:
      name: laptop-agent

    steps:

    - checkout: self

    - script: |

        aws eks update-kubeconfig \
        --region $(AWS_REGION) \
        --name $(EKS_CLUSTER)

      displayName: "Connect"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

    - script: |

        kubectl apply \
        -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

      displayName: "Install"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

    - script: |

        kubectl patch deployment metrics-server \
        -n kube-system \
        --type=json \
        -p='[{"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--kubelet-insecure-tls"}]'

      displayName: "Patch"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

    - script: |

        kubectl rollout status \
        deployment/metrics-server \
        -n kube-system \
        --timeout=180s

      displayName: "Wait"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

    - script: |

        kubectl top nodes

      displayName: "Verify"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)