stages:

- stage: Monitoring

  displayName: "Monitoring"

  dependsOn: GitOpsDeployment


  jobs:

  - job: InstallMonitoring

    displayName: "Install Monitoring"

    pool:
      name: laptop-agent


    steps:

    - checkout: self


# CONNECT

    - script: |

        aws eks update-kubeconfig \
        --region $(AWS_REGION) \
        --name $(EKS_CLUSTER)

      displayName: "Connect"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)



# INSTALL PROMETHEUS LIGHT

    - script: |

        helm repo add prometheus-community \
        https://prometheus-community.github.io/helm-charts

        helm repo add grafana \
        https://grafana.github.io/helm-charts

        helm repo update


        helm upgrade \
        --install \
        prometheus \
        prometheus-community/prometheus \
        \
        --namespace monitoring \
        --create-namespace \
        \
        --set alertmanager.enabled=false \
        \
        --set pushgateway.enabled=false \
        \
        --set kubeStateMetrics.enabled=false \
        \
        --set server.persistentVolume.enabled=false \
        \
        --set server.replicaCount=1 \
        \
        --set server.resources.requests.memory=256Mi \
        \
        --set server.resources.requests.cpu=200m \
        \
        --set prometheus-node-exporter.resources.requests.memory=32Mi

      displayName: "Install Prometheus"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)



# INSTALL GRAFANA LIGHT

    - script: |

        helm upgrade \
        --install \
        grafana \
        grafana/grafana \
        \
        --namespace monitoring \
        \
        --set replicas=1 \
        \
        --set persistence.enabled=false \
        \
        --set service.type=ClusterIP \
        \
        --set resources.requests.memory=64Mi \
        \
        --set resources.requests.cpu=50m

      displayName: "Install Grafana"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)



# WAIT

    - script: |

        aws eks update-kubeconfig \
        --region $(AWS_REGION) \
        --name $(EKS_CLUSTER)

        kubectl wait \
        --for=condition=ready \
        pod \
        -l app.kubernetes.io/name=grafana \
        -n monitoring \
        --timeout=80s

      displayName: "Wait"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)



# SHOW LOGIN

    - script: |

        PASS=$(
        kubectl get secret \
        -n monitoring \
        grafana \
        -o jsonpath="{.data.admin-password}" \
        | base64 -d
        )

        echo ""
        echo "RUN:"
        echo ""

        echo "kubectl port-forward svc/grafana -n monitoring 3000:80"

        echo ""

        echo "URL:"
        echo "http://localhost:3000"

        echo ""

        echo "USER:"
        echo "admin"

        echo ""

        echo "PASS:"
        echo $PASS

      displayName: "Show Login"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)