stages:

- stage: Rollback

  displayName: "Failure Recovery"

  dependsOn: HPA

  jobs:

  - job: PrepareRollback

    displayName: "Validate And Recover"

    pool:
      name: laptop-agent

    steps:

    - checkout: self

# CONNECT
    - script: |

        export AWS_DEFAULT_REGION=$(AWS_REGION)

        aws eks update-kubeconfig \
          --region $(AWS_REGION) \
          --name $(EKS_CLUSTER)

      displayName: "Connect"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)


# SHOW HISTORY

    - script: |

        echo ""
        echo "VOTE HISTORY"

        kubectl rollout history \
        deployment/vote

        echo ""

        echo "RESULT HISTORY"

        kubectl rollout history \
        deployment/result

      displayName: "Show Rollback History"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

# VERIFY HEALTH
    - script: |

        FAILED=0

        kubectl rollout status \
          deployment/vote \
          --timeout=60s \
          || FAILED=1

        kubectl rollout status \
          deployment/result \
          --timeout=60s \
          || FAILED=1

        echo "##vso[task.setvariable variable=rollback_needed]$FAILED"

      displayName: "Validate Deployment"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

# ROLLBACK

    - script: |

        echo ""
        echo "ROLLBACK STARTED"

        kubectl rollout undo \
          deployment/vote

        kubectl rollout undo \
          deployment/result

      condition: |
        eq(
          variables['rollback_needed'],
          '1'
        )

      displayName: "Rollback"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

# VERIFY RECOVERY
    - script: |

        kubectl rollout status \
          deployment/vote \
          --timeout=90s

        kubectl rollout status \
          deployment/result \
          --timeout=90s

        kubectl get deployment

        kubectl get pods

      condition: |
        eq(
          variables['rollback_needed'],
          '1'
        )

      displayName: "Verify Recovery"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

# SUCCESS
    - script: |

        echo ""
        echo "PIPELINE COMPLETED"

      condition: |
        eq(
          variables['rollback_needed'],
          '0'
        )

      displayName: "Finish"

      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)