stages:

- stage: TerraformSecurity

  displayName: "Terraform Security"

  dependsOn: TerraformValidation

  jobs:

# --------------------------------

  - job: Checkov

    displayName: "Run Checkov"

    pool:
      name: laptop-agent

    steps:

    - checkout: self

    - script: |

        FAILED=0

        cd terraform

        checkov \
        -d . \
        || FAILED=1


        echo "##vso[task.setvariable variable=tf_security_failed;isOutput=true]$FAILED"

      displayName: "Terraform Security"

      name: checkov

# --------------------------------

  - job: TerraformApproval

    displayName: "Terraform Security Approval"

    dependsOn: Checkov

    pool: server

    condition: |
      eq(
      dependencies.Checkov.outputs['checkov.tf_security_failed'],
      '1'
      )

    steps:

    - task: ManualValidation@0

      timeoutInMinutes: 60

      inputs:

        notifyUsers: ''

        instructions: |

          Terraform security findings detected.

          Review Checkov report.

          Approve → Continue

          Reject → Stop

        onTimeout: reject

# --------------------------------

  - job: FinalizeTerraformSecurity

    displayName: "Finalize"

    dependsOn:

    - Checkov
    - TerraformApproval

    condition: |
      or(
      succeeded('Checkov'),
      succeeded('TerraformApproval')
      )

    pool:
      name: laptop-agent

    steps:

    - script: |

        echo "Terraform security completed"

      displayName: "Continue"