stages:

- stage: TerraformProvision

  displayName: "Infrastructure Provision"

  dependsOn: TerraformSecurity

  jobs:

# -------------------------

  - job: Approval

    displayName: "Infrastructure Approval"

    pool: server

    steps:

    - task: ManualValidation@0

      timeoutInMinutes: 120

      inputs:

        notifyUsers: ''

        instructions: |

          Infrastructure Action:

          TF_ACTION=$(TF_ACTION)

          Approve → Execute

          Reject → Stop

        onTimeout: reject

# -------------------------

  - job: Provision

    displayName: "Terraform Execute"

    dependsOn: Approval

    pool:
      name: laptop-agent

    steps:

    - checkout: self

# AWS

    - script: |

        export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)

        export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)

        export AWS_DEFAULT_REGION=$(AWS_REGION)

        aws sts get-caller-identity

      displayName: "Verify AWS"

# APPLY

    - script: |

        cd terraform

        terraform init

        if [ "$(TF_ACTION)" = "apply" ]
        then

          terraform apply -auto-approve

        elif [ "$(TF_ACTION)" = "destroy" ]
        then

          terraform destroy -auto-approve

        else

          echo "Skipping"

        fi

      displayName: "Apply / Destroy"